use test-python workflow for unit tests
Signed-off-by: Brian Gallagher <briangal@gmail.com>

diff --git a/.github/workflows/test-python.yaml b/.github/workflows/test-python.yaml
--- a/.github/workflows/test-python.yaml
+++ b/.github/workflows/test-python.yaml
@@ -16,6 +16,20 @@ jobs:
         with:
           python-version: '3.9'
 
+      - name: Install uv and create virtual environment
+        run: |
+          make uv
+          make uv-venv
 
       - name: Verify
         run: make verify
+
+      - name: Run Tests
+        run: |
+          make test-python xml=true
+
+      - name: Upload coverage to Coveralls
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          coveralls --verbose || echo "Coveralls report failed"
